import { withDangerousMod } from '@expo/config-plugins';
import * as fs from 'fs';
import * as path from 'path';
import type { ConfigPlugin } from '@expo/config-plugins';

const REQUIRE_BLOCK_START = '# @wwdrew/react-native-spotify-sdk require begin';
const REQUIRE_BLOCK_END = '# @wwdrew/react-native-spotify-sdk require end';
const INSTALL_BLOCK_START = '# @wwdrew/react-native-spotify-sdk install begin';
const INSTALL_BLOCK_END = '# @wwdrew/react-native-spotify-sdk install end';
const SPOTIFY_POD_REGEX = /^\s*pod\s+['"]SpotifyiOS['"]/m;
const LEGACY_AUTOGENERATED_POD_REGEX =
  /^\s*pod\s+['"]SpotifyiOS['"][^\n]*@wwdrew\/react-native-spotify-sdk\/podspecs[^\n]*\n?/gm;

function createRequireBlock(): string {
  const requireLine =
    "require (File.exist?(File.expand_path('../../ios/spotify_sdk_pods.rb', __dir__)) ? File.expand_path('../../ios/spotify_sdk_pods.rb', __dir__) : File.expand_path('../node_modules/@wwdrew/react-native-spotify-sdk/ios/spotify_sdk_pods.rb', __dir__))";

  return [REQUIRE_BLOCK_START, requireLine, REQUIRE_BLOCK_END].join('\n');
}

function createInstallBlock(): string {
  return [
    INSTALL_BLOCK_START,
    'install_spotify_sdk_pods!',
    INSTALL_BLOCK_END,
  ].join('\n');
}

function replaceManagedBlockIfPresent(
  podfileContents: string,
  blockStart: string,
  blockEnd: string,
  replacement: string
): string | null {
  const blockRegex = new RegExp(`${blockStart}[\\s\\S]*?${blockEnd}`, 'm');
  if (!blockRegex.test(podfileContents)) {
    return null;
  }

  return podfileContents.replace(blockRegex, replacement);
}

function insertRequireBlock(
  podfileContents: string,
  requireBlock: string
): string {
  const firstTargetRegex = /^target\s+['"][^'"]+['"]\s+do[^\n]*$/m;
  const targetMatch = podfileContents.match(firstTargetRegex);
  if (targetMatch?.index !== undefined) {
    const insertAt = targetMatch.index;
    return (
      `${podfileContents.slice(0, insertAt)}` +
      `${requireBlock}\n\n` +
      `${podfileContents.slice(insertAt)}`
    );
  }

  const platformRegex = /^platform\s*:ios[^\n]*$/m;
  const platformMatch = podfileContents.match(platformRegex);
  if (platformMatch?.index !== undefined) {
    const insertAt = platformMatch.index + platformMatch[0].length;
    return (
      `${podfileContents.slice(0, insertAt)}\n\n` +
      `${requireBlock}\n` +
      `${podfileContents.slice(insertAt)}`
    );
  }

  const prepareRegex = /^prepare_react_native_project!\s*$/m;
  const prepareMatch = podfileContents.match(prepareRegex);
  if (prepareMatch?.index !== undefined) {
    const insertAt = prepareMatch.index;
    return (
      `${podfileContents.slice(0, insertAt)}` +
      `${requireBlock}\n\n` +
      `${podfileContents.slice(insertAt)}`
    );
  }

  throw new Error(
    'Unable to find safe insertion point in Podfile for Spotify SDK require block.'
  );
}

function insertInstallBlock(
  podfileContents: string,
  installBlock: string
): string {
  const useExpoRegex = /^\s*use_expo_modules!\s*$/m;
  const useExpoMatch = podfileContents.match(useExpoRegex);
  if (useExpoMatch?.index !== undefined) {
    const insertAt = useExpoMatch.index;
    return (
      `${podfileContents.slice(0, insertAt)}` +
      `${installBlock}\n` +
      `${podfileContents.slice(insertAt)}`
    );
  }

  const firstTargetRegex = /^target\s+['"][^'"]+['"]\s+do[^\n]*$/m;
  const targetMatch = podfileContents.match(firstTargetRegex);
  if (targetMatch?.index !== undefined) {
    const insertAt = targetMatch.index + targetMatch[0].length;
    return (
      `${podfileContents.slice(0, insertAt)}\n` +
      `${installBlock}\n` +
      `${podfileContents.slice(insertAt)}`
    );
  }

  throw new Error(
    'Unable to find safe insertion point in Podfile for Spotify SDK install block.'
  );
}

function validateManagedPodState(podfileContents: string): void {
  const requireStartCount = (
    podfileContents.match(new RegExp(REQUIRE_BLOCK_START, 'g')) ?? []
  ).length;
  const requireEndCount = (
    podfileContents.match(new RegExp(REQUIRE_BLOCK_END, 'g')) ?? []
  ).length;
  const installStartCount = (
    podfileContents.match(new RegExp(INSTALL_BLOCK_START, 'g')) ?? []
  ).length;
  const installEndCount = (
    podfileContents.match(new RegExp(INSTALL_BLOCK_END, 'g')) ?? []
  ).length;
  const spotifyMatches = podfileContents.match(
    /^\s*pod\s+['"]SpotifyiOS['"][^\n]*$/gm
  );

  if (requireStartCount !== requireEndCount) {
    throw new Error('Spotify Podfile require markers are imbalanced.');
  }

  if (installStartCount !== installEndCount) {
    throw new Error('Spotify Podfile install markers are imbalanced.');
  }

  if (requireStartCount > 1 || installStartCount > 1) {
    throw new Error(
      'Spotify Podfile managed marker blocks should appear at most once.'
    );
  }

  if ((spotifyMatches?.length ?? 0) > 1) {
    throw new Error(
      'Detected multiple SpotifyiOS pod declarations in Podfile. Please keep exactly one.'
    );
  }
}

export function transformSpotifyPodfile(podfile: string): string {
  let nextPodfile = podfile;
  const requireBlock = createRequireBlock();
  const installBlock = createInstallBlock();

  // Migrate legacy plugin-generated direct pod lines to helper-based install.
  if (LEGACY_AUTOGENERATED_POD_REGEX.test(nextPodfile)) {
    nextPodfile = nextPodfile.replace(LEGACY_AUTOGENERATED_POD_REGEX, '');
  }

  const replacedRequire = replaceManagedBlockIfPresent(
    nextPodfile,
    REQUIRE_BLOCK_START,
    REQUIRE_BLOCK_END,
    requireBlock
  );
  if (replacedRequire !== null) {
    nextPodfile = replacedRequire;
  }

  const replacedInstall = replaceManagedBlockIfPresent(
    nextPodfile,
    INSTALL_BLOCK_START,
    INSTALL_BLOCK_END,
    installBlock
  );
  if (replacedInstall !== null) {
    nextPodfile = replacedInstall;
  }

  const hasManagedRequire = nextPodfile.includes(REQUIRE_BLOCK_START);
  const hasManagedInstall = nextPodfile.includes(INSTALL_BLOCK_START);
  const hasManualSpotifyPod = SPOTIFY_POD_REGEX.test(nextPodfile);
  const hasInstallCall = /^\s*install_spotify_sdk_pods!\s*$/m.test(nextPodfile);

  if (!hasManagedRequire) {
    nextPodfile = insertRequireBlock(nextPodfile, requireBlock);
  }

  // Respect existing manual declarations/calls and avoid duplicates.
  if (!hasManualSpotifyPod && !hasInstallCall && !hasManagedInstall) {
    nextPodfile = insertInstallBlock(nextPodfile, installBlock);
  }

  validateManagedPodState(nextPodfile);
  return nextPodfile;
}

const withSpotifyPodfile: ConfigPlugin = (config) => {
  return withDangerousMod(config, [
    'ios',
    async (config) => {
      const podfilePath = path.join(
        config.modRequest.platformProjectRoot,
        'Podfile'
      );

      const podfile = fs.readFileSync(podfilePath, 'utf8');
      const nextPodfile = transformSpotifyPodfile(podfile);

      if (nextPodfile !== podfile) {
        fs.writeFileSync(podfilePath, nextPodfile);
      }

      return config;
    },
  ]);
};

export default withSpotifyPodfile;
